[project]
name = "msme"
version = "0.1.0"
description = "msme Client Instance"
requires-python = ">=3.10"
dependencies = [
    "sales",
    "inventory",
    "supply_chain",
    "settings",
]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["msme"]
