[project]
name = "bes-factory"
version = "0.1.0"
description = "Modular BES Factory Monorepo"
requires-python = ">=3.10"
dependencies = [
    "sqlmodel",
    "fastapi",
    "uvicorn",
    "pydantic",
    "aiosqlite>=0.22.1",
    "asyncpg>=0.31.0",
    "greenlet>=3.5.0",
    "python-jose[cryptography]>=3.5.0",
    "passlib[bcrypt]>=1.7.4",
    "python-multipart>=0.0.27",
    "bcrypt<4.0.0",
    "jinja2"
]

[tool.pdm]
distribution = false

[tool.pdm.workspace]
packages = [
    "core",
    "extensions/*",
    "instances/*"
]


[dependency-groups]
dev = [
    "-e file:///${PROJECT_ROOT}/core",
    "-e file:///${PROJECT_ROOT}/extensions/sales",
    "-e file:///${PROJECT_ROOT}/extensions/settings",
    "-e file:///${PROJECT_ROOT}/instances/test_custom",
    "-e file:///${PROJECT_ROOT}/extensions/finance",
    "-e file:///${PROJECT_ROOT}/extensions/ai",
    "-e file:///${PROJECT_ROOT}/extensions/supply_chain",
    "-e file:///${PROJECT_ROOT}/extensions/inventory",
]


