[project]
name = "msme-custom"
version = "0.1.0"
description = "msme custom Client Instance"
requires-python = ">=3.10"
dependencies = [
    "inventory",
    "supply_chain",
    "ai",
    "settings",
]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["msme_custom"]
